USE ROLE ACCOUNTADMIN;

-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE HOL_ROLE;
GRANT ROLE HOL_ROLE TO ROLE SYSADMIN;
GRANT ROLE HOL_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE HOL_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HOL_ROLE;

-- Databases
CREATE OR REPLACE DATABASE SCRAPED_DATA;
GRANT OWNERSHIP ON DATABASE SCRAPED_DATA TO ROLE HOL_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE CITA WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE CITA TO ROLE HOL_ROLE;


-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
USE ROLE HOL_ROLE;
USE WAREHOUSE CITA;
USE DATABASE SCRAPED_DATA;

-- Schemas
CREATE OR REPLACE SCHEMA EXTERNAL;

CREATE OR REPLACE SCHEMA ANALYTICS;

CREATE OR REPLACE SCHEMA JOBS;

-- test