
create TABLE SCRAPED_DATA.JOBS.US_JOBS (
	COMPANY_NAME VARCHAR,
	JOB_TITLE VARCHAR,
	LOCATION VARCHAR,
	COMPANY_DOMAIN VARCHAR,
	JOB_URL VARCHAR,
	POSTED_ON DATE,
	JOB_ID NUMBER,
	CITY VARCHAR,
	STATE VARCHAR
);

